#include QMK_KEYBOARD_H

#include <sendstring_french.h>

/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk-compile-json. You may or may not want to
 * edit it directly.
 */
enum custom_keycodes {
  PY_BASIC_I = SAFE_RANGE,
  PY_ADV_I,
  PY_KERN_I,
  PY_ARR,
  LT_BS,//boldsymbol
  LT_MB,//mathbf
  LT_EQ,//equation
  LT_WIDTH,//Sizing images
  LT_HEIGHT,//Sizing images
  LT_DLA
  //Improved multi-function layer key
};

enum {
    TD_SL = 0
};


typedef struct {
  bool is_press_action;
  int state;
} tap;

//Define a type for as many tap dance states as you need
enum {
  SINGLE_TAP = 1,
  SINGLE_HOLD = 2,
  DOUBLE_TAP = 3,
  DOUBLE_HOLD = 4
};

//Declare the functions to be used with your tap dance key(s)

//Function associated with all tap dances
int cur_dance (qk_tap_dance_state_t *state);

//Functions associated with individual tap dances
void ql_finished (qk_tap_dance_state_t *state, void *user_data);
void ql_reset (qk_tap_dance_state_t *state, void *user_data);
 

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [0] = LAYOUT(KC_ESC, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, KC_MINS,
            KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_EQL,
            KC_BSLS, KC_A, KC_S, KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, KC_SCLN, KC_QUOT,
            KC_LSFT, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, KC_LBRC,
            KC_LCTL, KC_LGUI, KC_LALT, KC_NUHS, TD(TD_SL), KC_BSPC, KC_DEL, KC_RSFT, KC_SPC, KC_RALT, KC_RBRC, KC_QUOT, KC_RSFT, KC_ENT),
    [1] = LAYOUT(TO(0), KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F6, KC_F7, KC_F8, KC_F9, KC_F10, KC_F11,
            KC_TAB, PY_BASIC_I, PY_ADV_I, PY_KERN_I, KC_TRNS, KC_PERC, KC_HASH, KC_TRNS, TO(0), KC_TRNS, KC_TRNS, KC_F12,
            KC_TRNS, KC_TRNS, KC_HOME, KC_LEFT, KC_DOWN, KC_TRNS, KC_TRNS, KC_UP, KC_RGHT, KC_END, KC_TRNS, KC_TRNS,
            KC_TRNS, KC_LT, KC_GT, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
            KC_TRNS, KC_TRNS, KC_GRV, TO(2), TO(0), TO(0), KC_TRNS, TO(0), KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),
    [2] = LAYOUT(TO(0), KC_NO, KC_NO, KC_NO, KC_NO, KC_NLCK, TO(0), TO(0), KC_PSLS, KC_PAST, KC_PMNS, KC_NO,
            KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_P7, KC_P8, KC_P9, KC_PPLS, KC_NO,
            KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_P4, KC_P5, KC_P6, KC_PCMM, KC_NO,
            KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_P1, KC_P2, KC_P3, KC_PEQL, KC_NO, KC_TRNS,
            KC_TRNS, KC_TRNS, KC_NO, TO(3), KC_BSPC, KC_TRNS, KC_ENT, KC_SPC, KC_P0, KC_P0, KC_PDOT, KC_PENT, KC_ENT),
    [3] = LAYOUT(TO(0), KC_ESC, KC_ACL0, KC_ACL1, KC_ACL2, KC_NO, TO(0), KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
            KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_WH_D, KC_WH_U, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
            KC_NO, KC_NO, KC_NO, KC_MS_L, KC_MS_D, KC_WH_U, KC_WH_D, KC_MS_U, KC_MS_R, KC_NO, KC_NO, KC_NO,
            KC_LSFT, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
            KC_LCTL, KC_LGUI, KC_LALT, KC_NO, TO(4), KC_BTN1, KC_WH_L, KC_WH_R, KC_BTN2, KC_BTN3, KC_NO, KC_NO, KC_NO, KC_ENT),
    [4] = LAYOUT(TO(0), KC_ESC, KC_1, KC_2, KC_3, KC_4, KC_LGUI, KC_NO, KC_NO, KC_NO, KC_NO, KC_LGUI,
            KC_TAB, KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
            KC_J, KC_NO, KC_A, KC_S, KC_D, KC_F, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
            KC_LSFT, KC_LSFT, KC_Z, KC_X, KC_C, KC_V, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_LCTL,
            KC_LCTL, KC_LALT, KC_LALT, KC_TRNS, KC_SPC, KC_TRNS, KC_ENT, KC_LGUI, KC_NO, KC_NO, KC_NO, KC_NO, KC_ENT),
//Special macro
    [5] = LAYOUT(TO(0), KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, KC_MINS, 
            KC_TAB, PY_ARR, KC_W, LT_EQ, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_EQL,
            KC_BSLS, KC_A, LT_BS, LT_DLA, KC_F, KC_G, LT_HEIGHT, KC_J, KC_K, KC_L, LT_MB, KC_QUOT,
            KC_LSFT, LT_WIDTH, KC_X, KC_C, KC_V, KC_B, KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, KC_LBRC,
            KC_LCTL, KC_LGUI, KC_LALT, KC_NUHS, TO(1), KC_BSPC, KC_DEL, KC_RSFT, KC_SPC, KC_RALT, KC_RBRC, KC_QUOT, KC_RSFT, KC_ENT),
};


bool process_record_user(uint16_t keycode, keyrecord_t *record) {
  switch (keycode) {
    //The Python macros
    case PY_BASIC_I:
      if (record->event.pressed) {
        // when keycode PY_BASIC_I is pressed
        send_string("import numpy as np\nimport matplotlib.pyplot as plt\n");
      } else {
        // when keycode PY_BASIC_I is released
      }
      break;
    case PY_ADV_I:
      if (record->event.pressed) {
        send_string("import sympy as sp\nfrom time import time\nfrom tqdm import tqdm\nimport os\n");
      } else {
      }
      break;
    case PY_KERN_I:
      if (record->event.pressed) {
        send_string("import xara\nimport saro\nimport kernuller\n");
      } else {
      }
      break;
    case PY_ARR:
      if (record->event.pressed) {
        send_string( SS_LCTL("xv") " = np.array(" SS_LCTL("v") ")");
      } else {
      }
      break;
      //The LaTeX macros
    case LT_BS:
      if (record->event.pressed) {
        send_string(SS_RALT("_") "boldsymbol{}" SS_TAP(X_LEFT));
      } else {
      }
      break;
    case LT_MB:
      if (record->event.pressed) {
        send_string(SS_RALT("_") "mathbf{}" SS_TAP(X_LEFT));
      } else {
      }
      break;
    case LT_EQ:
      if (record->event.pressed) {
        send_string(SS_RALT("_") "begin{equation}\n\n" SS_RALT("_") "begin{equation}" SS_TAP(X_UP) SS_TAP(X_TAB));
      } else {
      }
      break;
    case LT_WIDTH:
      if (record->event.pressed) {
        send_string("[width=0.45" SS_RALT("_") "textwidth]");
      } else {
      }
      break;
    case LT_HEIGHT:
      if (record->event.pressed) {
        send_string("[height=0.45" SS_RALT("_") "textheight]");
      } else {
      }
      break;
    case LT_DLA:
      if (record->event.pressed) {
        send_string(SS_RALT("_") "footnote{De l'anglais " SS_RALT("_") "textit{}}" SS_TAP(X_LEFT) SS_TAP(X_LEFT));
      } else {
      }
      break;
  }
  return true;
};


//Determine the current tap dance state
int cur_dance (qk_tap_dance_state_t *state) {
  if (state->count == 1) {
    if (!state->pressed) {
      return SINGLE_TAP;
    } else {
      return SINGLE_HOLD;
    }
  } else if (state->count == 2) {
    if (!state->pressed) {
      return DOUBLE_TAP;
    } else {
      return DOUBLE_HOLD;
    }
  } else return 8;
  
}

//Initialize tap structure associated with example tap dance key
static tap ql_tap_state = {
  .is_press_action = true,
  .state = 0
};

//Functions that control what our tap dance key does
void ql_finished (qk_tap_dance_state_t *state, void *user_data) {
  ql_tap_state.state = cur_dance(state);
  switch (ql_tap_state.state) {
    case SINGLE_TAP: 
      layer_move(1); 
      break;
    case SINGLE_HOLD: 
      layer_clear();
      layer_on(1);
      break;
    case DOUBLE_TAP: 
      layer_clear();
      layer_on(2);
      break;
    case DOUBLE_HOLD: 
      layer_clear();
      layer_on(5);
  }
};

void ql_reset (qk_tap_dance_state_t *state, void *user_data) {
  //if the key was held down and now is released then switch off the layer
  switch (ql_tap_state.state) {
      case SINGLE_HOLD:
        layer_clear();
        layer_on(0);
        break;
      case DOUBLE_HOLD:
        layer_clear();
        layer_on(0);
  }
  ql_tap_state.state = 0;
};

//Associate our tap dance key with its functionality
qk_tap_dance_action_t tap_dance_actions[] = {
    [TD_SL] = ACTION_TAP_DANCE_FN_ADVANCED_TIME(NULL, ql_finished, ql_reset, 200)
    };
